##############################################################################
#
# Assignment and Constraints Quartus TCL script for design H:\Advanced Computer Systems Engineering\DonB\HandleC\Video\EDIF\Video.edf
#
# Generated by DK Design Suite (Version 5.5_1.7474.19994)
# Timestamp 2013 10 14 5 51 33
#
##############################################################################


# Set family and part
set_global_assignment -name FAMILY "CYCLONE III"
set_global_assignment -name DEVICE "EP4CE115F29C7"

# Set compilation options
set_global_assignment -name ALLOW_POWER_UP_DONT_CARE Off
set_global_assignment -name AUTO_PACKED_REGISTERS Normal


############################### IO assignments ###############################

set_location_assignment PIN_Y2 -to PIN_Y2
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_Y2
set_location_assignment PIN_G6 -to PIN_G6
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_G6
set_location_assignment PIN_H5 -to PIN_H5
set_instance_assignment -name IO_STANDARD "LVTTL" -to PIN_H5
set_location_assignment PIN_H10 -to PIN_H10
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_H10
set_location_assignment PIN_H8 -to PIN_H8
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_H8
set_location_assignment PIN_J12 -to PIN_J12
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_J12
set_location_assignment PIN_G10 -to PIN_G10
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_G10
set_location_assignment PIN_F12 -to PIN_F12
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_F12
set_location_assignment PIN_D10 -to PIN_D10
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_D10
set_location_assignment PIN_E11 -to PIN_E11
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_E11
set_location_assignment PIN_E12 -to PIN_E12
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_E12
set_location_assignment PIN_C9 -to PIN_C9
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_C9
set_location_assignment PIN_F10 -to PIN_F10
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_F10
set_location_assignment PIN_B8 -to PIN_B8
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_B8
set_location_assignment PIN_C8 -to PIN_C8
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_C8
set_location_assignment PIN_H12 -to PIN_H12
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_H12
set_location_assignment PIN_F8 -to PIN_F8
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_F8
set_location_assignment PIN_G11 -to PIN_G11
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_G11
set_location_assignment PIN_G8 -to PIN_G8
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_G8
set_location_assignment PIN_D12 -to PIN_D12
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_D12
set_location_assignment PIN_D11 -to PIN_D11
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_D11
set_location_assignment PIN_C12 -to PIN_C12
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_C12
set_location_assignment PIN_A11 -to PIN_A11
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_A11
set_location_assignment PIN_B11 -to PIN_B11
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_B11
set_location_assignment PIN_C11 -to PIN_C11
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_C11
set_location_assignment PIN_A10 -to PIN_A10
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_A10
set_location_assignment PIN_B10 -to PIN_B10
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_B10
set_location_assignment PIN_A12 -to PIN_A12
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_A12
set_location_assignment PIN_G13 -to PIN_G13
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_G13
set_location_assignment PIN_C13 -to PIN_C13
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_C13
set_location_assignment PIN_F11 -to PIN_F11
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_F11
set_location_assignment PIN_C10 -to PIN_C10
set_instance_assignment -name IO_STANDARD "2.5-V" -to PIN_C10


############################# Timing requirements ############################

timegroup CelSynTimeGroup1 -add_member B7_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B10_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B11_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B12_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B13_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B14_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B15_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B16_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B17_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B8_Demo_hcc_40_DTYPE0IR
timegroup CelSynTimeGroup2 -add_member B9_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B10_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B11_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B12_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B13_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B14_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B15_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B16_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B17_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B8_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name X_ON_VIOLATION_OPTION OFF -to B9_Demo_hcc_40_DTYPE0IR
set_instance_assignment -name MAX_DELAY -from CelSynTimeGroup2 -to CelSynTimeGroup1 2.000ns
set_instance_assignment -name MAX_DELAY -from CelSynTimeGroup2 -to CelSynTimeGroup2 2.000ns
